name: LGWLoadBalancer
version: '${version}'
main: net.azisaba.lgwloadbalancer.LGWLoadBalancer
api-version: '1.16'
authors: [ sysnote8 ]
description: player load balancer
depend: [ "CommandAPI" ]
permissions:
  lgwloadbalancer.cmd.lgwlb.go:
    default: true
  lgwloadbalancer.cmd.lgwlb.*:
    default: op