name: LGWLoadBalancer
version: '${version}'
main: net.azisaba.lgwloadbalancer.LGWLoadBalancer
api-version: '1.16'
authors: [ sysnote8 ]
description: player load balancer
commands:
  lgwlb:
    permission: lgwloadbalancer.cmd.lgwlb
permissions:
  lgwloadbalancer.cmd.lgwlb.go:
    default: true
  lgwloadbalancer.cmd.lgwlb.stat:
    default: op